[tool.poetry]
name = "training2"
version = "0.1.0"
description = ""
authors = ["Sina Bakhshmand <Sina.Bakhshmand@now-gmbh.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

